# This is action publishes the current GitHub Dependabot alerts to a CSV file.

name: Dependabot-Publish-Alerts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dependabot-alert-export:
    runs-on: ubuntu-latest
    steps:
      - name: Export Dependabot alerts
        uses: robertcrockett/dependabot-alert-export@v2
        with:
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
          org_name: "woodrbe"
          repo_name: "terraform"
          csv_path: data/vulnerability.csv

      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability_report
          path: data/vulnerability.csv
